baseURL = "https://riyuzakii.github.io/"
locale = "en-us"
title = "Aditya Rohan"
enableRobotsTXT = true
disableKinds = ["taxonomy", "term"]

[permalinks]
  posts = "/:slug/"

[params]
  description = "Notes on what I've been working on."

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  noClasses = false
  lineNos = false
  tabWidth = 2

[[menu.main]]
  name = "writing"
  url = "/"
  weight = 1

[[menu.main]]
  name = "about"
  url = "/about/"
  weight = 2
